### ISSUE TITLE
Searching for the coin you want.

### ISSUE THREAD

**Issue by Dannation** [pbojan/cryptocoins-desklet-cinnamon#1]
So I was trying to add Verge, and I spent a fair bit of time searching through the list of cryptos in the settings menu, and could not find it.  Right as I was about to close to the window and assume it wasn't in the list, I found it, I believe it's the 72nd one on the list.

Anyway, I know it looks better with BTC and the other big coins high in the list, but not having the coins in alphabetical order can result in an annoying forced scan of every entry in the list if the coin you're looking for doesn't immediately jump out to you.

Regardless, thanks again for your great work with this desklet, for being the only crypto ticker desklet that I'm aware of, you really went above and beyond to deliver a quality little package.  :+1:

**Comment by pbojan** [comment]
Yes, you are right the ordering is confusing. As there is no easy way to add autocomplete or some different better input field I have reordered the coins alphabetically but still keep few of the most popular coins on the top. Thanks for the feedback, hope this helps!
