### ISSUE TITLE
Wrong desklet proportions

### ISSUE THREAD

**Issue by malteo** [pbojan/cryptocoins-desklet-cinnamon#3]
I'm using the desklet on latest cinnamon (3.8.3) on Arch Linux, the proportions of the icon and the desklet size seem wrong...

![image](https://user-images.githubusercontent.com/80266/40471725-ce2d7a86-5f37-11e8-89c9-e7b3a1862fe0.png)

Other desklets work OK

**Comment by pbojan** [comment]
@malteo can you please tell me your resolution and if you are using any scaling? The desklet looks like it has the wrong width. Did you also try to remove and re-add it again?

**Comment by malteo** [comment]
I'm on a 3840x2160 resolution with cinnamon "Auto" scaling enabled, so HiDPI. Yes I already tried re-adding it.

**Comment by pbojan** [comment]
@malteo can you please try to disable the auto-scaling and see if that will solve the issue?

**Comment by malteo** [comment]
Yes! It does. But as soon as I switch scaling to `Double` it changes to wrong proprtions.

**Comment by pbojan** [comment]
@malteo thanks for the feedback! Will try to find a way to fix it.
