### ISSUE TITLE
having trouble adding desklet to the desktop

### ISSUE THREAD

**Issue by jeffclifton** [pbojan/cryptocoins-desklet-cinnamon#4]
I am new to linux.  I am running linux mint, and am trying to add the crypto coins ticker desklet.  I am adding it to my desktop, but it does not appear.  It will allow me to configure it, but it still doesn't appear.  Thank you for your help,
Jeff

**Comment by pbojan** [comment]
Hey @jeffclifton, what version of Linux Mint Cinnamon do you have? Did you add other Desklets to the desktop to see if that works? If you add multiple instances they can be stacked so try moving them. On the newest version, you need to press the plus button from the bottom panel. If nothing works can you send me a screenshot from your Desklets Window?
