### ISSUE TITLE
"Loading coin data" - Desklet does not load data

### ISSUE THREAD

**Issue by cestocan** [pbojan/cryptocoins-desklet-cinnamon#6]
When using a VPN with an internet kill switch, the resulting delay in connecting to the internet seems to prevent the desklet from loading coin data during system startup. When the kill switch is disabled the isssue is resolved.  Is there a way to delay the startup of the desklet so that it attempts to load data AFTER the VPN has had a chance to fully connect to the internet?

**Comment by pbojan** [comment]
Hey, I am not aware of a way to do this would recommend checking if it is possible to delay all desklets from loading before the VPN connects otherwise you can use the Right-Click - Refresh button to refresh it manually. Do you have any problems with other Desklets?
