### ISSUE TITLE
Newer coins are not shown

### ISSUE THREAD

**Issue by mrxspice** [pbojan/cryptocoins-desklet-cinnamon#8]
New coins such as Solana or Serum or other DeFI coins cannot be found. It needs an update, these coins can be found everywhere Coinmarketcap, Coingecko, etc.. but in the widget they're missing...

**Comment by pbojan** [comment]
New coins and other cool improvements are coming with version 1.5! Just update it from the desklet settings when this PR is merged https://github.com/linuxmint/cinnamon-spices-desklets/pull/638.
